### ISSUE TITLE
failure to build with rust 1.94

### ISSUE THREAD

**Issue by landryb** [ulyssa/iamb#598]
building 0.0.11 on OpenBSD with rust 1.94, i get this build failure (sorry, large vomit):
```
error[E0275]: overflow evaluating the requirement `{async fn body of matrix_sdk::matrix_sdk_crypto::store::Store::get_sessions()}: std::marker::Send`                                                                                                                                       |                                                                                                                                                                                                                                                                                      = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`iamb`)                                                                                                                                                        note: required because it appears within the type `impl futures::Future<Output = Result<std::option::Option<Arc<tokio::sync::Mutex<Vec<matrix_sdk::matrix_sdk_crypto::Session>>>>, matrix_sdk::encryption::CryptoStoreError>>`                                                             --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/store/mod.rs:618:10                                                                                                                                                                             |                                                                                                                                                                                                                                                                                  618 |     ) -> Result<Option<Arc<Mutex<Vec<Session>>>>> {                                                                                                                                                                                                                                  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                               note: required because it's used within this `async` fn body                                                                                                                                                                                                                               --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1292:50                                                                                                                                                                          |                                                                                                                                                                                                                                                                                 1292 |       ) -> Result<(SessionType, String), OlmError> {                                                                                                                                                                                                                                 |  __________________________________________________^                                                                                                                                                                                                                            1293 | |         let existing_sessions = store.get_sessions(&sender_key.to_base64()).await?;                                                                                                                                                                                           1294 | |                                                                                                                                   
1295 | |         match message {                                                                                                                                                                                                                                                       
...    |                                                                                                                                                                                                                                                                               
1404 | |     }                                                                                                                                                                                                                                                                         
     | |_____^                                                                                                                                                                                                                                                                         
note: required because it's used within this `async` block
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1408:5
     |
1408 |     #[instrument(skip(self, store), fields(session, session_id))]
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `MaybeDangling<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_and_parse_olm_message::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/maybe_dangling.rs:76:11
note: required because it appears within the type `ManuallyDrop<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_and_parse_olm_message::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/manually_drop.rs:161:11
note: required because it appears within the type `Instrumented<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_and_parse_olm_message::{closure#0}::{closure#0}}>`
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/tracing-0.1.44/src/instrument.rs:266:16
     |
 266 |     pub struct Instrumented<T> {
     |                ^^^^^^^^^^^^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1416:53
     |
1416 |       ) -> OlmResult<(SessionType, DecryptionResult)> {
     |  _____________________________________________________^
1417 | |         let (session, plaintext) =
1418 | |             self.decrypt_olm_message(store, sender, sender_key, message).await?;
...    |
1452 | |     }
     | |_____^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1168:39
     |
1168 |       ) -> OlmResult<OlmDecryptionInfo> {
     |  _______________________________________^
1169 | |         let message_hash = OlmMessageHash::new(sender_key, ciphertext);
1170 | |
1171 | |         match self
...    |
1194 | |     }
     | |_____^
     = note: required for `Unique<impl futures::Future<Output = Result<matrix_sdk::matrix_sdk_crypto::olm::account::OlmDecryptionInfo, matrix_sdk::encryption::OlmError>>>` to implement `std::marker::Send`
note: required because it appears within the type `Box<impl futures::Future<Output = Result<matrix_sdk::matrix_sdk_crypto::olm::account::OlmDecryptionInfo, matrix_sdk::encryption::OlmError>>>`
    --> library/alloc/src/boxed.rs:234:11
note: required because it appears within the type `std::pin::Pin<Box<impl futures::Future<Output = Result<matrix_sdk::matrix_sdk_crypto::olm::account::OlmDecryptionInfo, matrix_sdk::encryption::OlmError>>>>`
    --> library/core/src/pin.rs:1094:11
note: required because it's used within this `async` block
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1214:5
     |
1214 |     #[instrument(skip_all, fields(sender, sender_key = ?content.sender_key))]
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `MaybeDangling<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_olm_v1::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/maybe_dangling.rs:76:11
note: required because it appears within the type `ManuallyDrop<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_olm_v1::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/manually_drop.rs:161:11
note: required because it appears within the type `Instrumented<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_olm_v1::{closure#0}::{closure#0}}>`
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/tracing-0.1.44/src/instrument.rs:266:16
     |
 266 |     pub struct Instrumented<T> {
     |                ^^^^^^^^^^^^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1221:39
     |
1221 |       ) -> OlmResult<OlmDecryptionInfo> {
     |  _______________________________________^
1222 | |         if content.recipient_key != self.static_data.identity_keys.curve25519 {
1223 | |             warn!("Olm event doesn't contain a ciphertext for our key");
...    |
1236 | |     }
     | |_____^
note: required because it's used within this `async` block
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1238:5
     |
1238 |     #[instrument(skip_all, fields(algorithm = ?event.content.algorithm()))]
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `MaybeDangling<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_to_device_event::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/maybe_dangling.rs:76:11
note: required because it appears within the type `ManuallyDrop<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_to_device_event::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/manually_drop.rs:161:11
note: required because it appears within the type `Instrumented<{async block@matrix_sdk::matrix_sdk_crypto::Account::decrypt_to_device_event::{closure#0}::{closure#0}}>`
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/tracing-0.1.44/src/instrument.rs:266:16
     |
 266 |     pub struct Instrumented<T> {
     |                ^^^^^^^^^^^^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/olm/account.rs:1244:39
     |
1244 |       ) -> OlmResult<OlmDecryptionInfo> {
     |  _______________________________________^
1245 | |         trace!("Decrypting a to-device event");
1246 | |
1247 | |         match &event.content {
...    |
1264 | |     }
     | |_____^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/machine/mod.rs:878:58
     |
 878 |       ) -> Result<OlmDecryptionInfo, DecryptToDeviceError> {
     |  __________________________________________________________^
 879 | |         // Decrypt the event
 880 | |         let mut decrypted = transaction
 881 | |             .account()
...    |
 892 | |         Ok(decrypted)
 893 | |     }
     | |_____^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/machine/mod.rs:1530:41
     |
1530 |       ) -> Option<ProcessedToDeviceEvent> {
     |  _________________________________________^
1531 | |         let decrypted = match self
1532 | |             .decrypt_to_device_event(transaction, &e, changes, decryption_settings)
1533 | |             .await
...    |
1594 | |         })
1595 | |     }
     | |_____^
note: required because it's used within this `async` block
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/machine/mod.rs:1471:5
     |
1471 |     #[instrument(skip_all, fields(sender, event_type, message_id))]
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `MaybeDangling<{async block@OlmMachine::receive_to_device_event::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/maybe_dangling.rs:76:11
note: required because it appears within the type `ManuallyDrop<{async block@OlmMachine::receive_to_device_event::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/manually_drop.rs:161:11
note: required because it appears within the type `Instrumented<{async block@OlmMachine::receive_to_device_event::{closure#0}::{closure#0}}>`
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/tracing-0.1.44/src/instrument.rs:266:16
     |
 266 |     pub struct Instrumented<T> {
     |                ^^^^^^^^^^^^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/machine/mod.rs:1478:41
     |
1478 |       ) -> Option<ProcessedToDeviceEvent> {
     |  _________________________________________^
1479 | |         Self::record_message_id(&raw_event);
1480 | |
1481 | |         let event: ToDeviceEvents = match raw_event.deserialize_as() {
...    |
1508 | |     }
     | |_____^
     = note: required for `Unique<impl futures::Future<Output = std::option::Option<ProcessedToDeviceEvent>>>` to implement `std::marker::Send`
note: required because it appears within the type `Box<impl futures::Future<Output = std::option::Option<ProcessedToDeviceEvent>>>`
    --> library/alloc/src/boxed.rs:234:11
note: required because it appears within the type `std::pin::Pin<Box<impl futures::Future<Output = std::option::Option<ProcessedToDeviceEvent>>>>`
    --> library/core/src/pin.rs:1094:11
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/machine/mod.rs:1712:60
     |
1712 |       ) -> OlmResult<(Vec<ProcessedToDeviceEvent>, Changes)> {
     |  ____________________________________________________________^
1713 | |         // Remove verification objects that have expired or are done.
1714 | |         let mut events: Vec<ProcessedToDeviceEvent> = self
1715 | |             .inner
...    |
1771 | |         Ok((events, changes))
1772 | |     }
     | |_____^
note: required because it's used within this `async` block
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/machine/mod.rs:1667:5
     |
1667 |     #[instrument(skip_all)]
     |     ^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `MaybeDangling<{async block@OlmMachine::receive_sync_changes::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/maybe_dangling.rs:76:11
note: required because it appears within the type `ManuallyDrop<{async block@OlmMachine::receive_sync_changes::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/manually_drop.rs:161:11
note: required because it appears within the type `Instrumented<{async block@OlmMachine::receive_sync_changes::{closure#0}::{closure#0}}>`
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/tracing-0.1.44/src/instrument.rs:266:16
     |
 266 |     pub struct Instrumented<T> {
     |                ^^^^^^^^^^^^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-crypto-0.14.0/src/machine/mod.rs:1672:69
     |
1672 |       ) -> OlmResult<(Vec<ProcessedToDeviceEvent>, Vec<RoomKeyInfo>)> {
     |  _____________________________________________________________________^
1673 | |         let mut store_transaction = self.inner.store.transaction().await;
1674 | |
1675 | |         let (events, changes) = self
...    |
1687 | |         Ok((events, room_key_updates))
1688 | |     }
     | |_____^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-base-0.14.1/src/response_processors/e2ee/to_device.rs:89:21
     |
  89 |   ) -> Result<Output> {
     |  _____________________^
  90 | |     let encryption_sync_changes = EncryptionSyncChanges {
  91 | |         to_device_events,
  92 | |         changed_devices: device_lists,
...    |
 136 | |     })
 137 | | }
     | |_^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-base-0.14.1/src/response_processors/e2ee/to_device.rs:64:21
     |
  64 |   ) -> Result<Output> {
     |  _____________________^
  65 | |     process(
  66 | |         olm_machine,
  67 | |         response.to_device.events.clone(),
...    |
  74 | |     .await
  75 | | }
     | |_^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-base-0.14.1/src/client.rs:583:31
     |
 583 |       ) -> Result<SyncResponse> {
     |  _______________________________^
...    |
 819 | |         Ok(response)
 820 | |     }
     | |_____^
note: required because it's used within this `async` block
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-base-0.14.1/src/client.rs:560:5
     |
 560 |     #[instrument(skip_all)]
     |     ^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `MaybeDangling<{async block@matrix_sdk_base::client::BaseClient::receive_sync_response::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/maybe_dangling.rs:76:11
note: required because it appears within the type `ManuallyDrop<{async block@matrix_sdk_base::client::BaseClient::receive_sync_response::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/manually_drop.rs:161:11
note: required because it appears within the type `Instrumented<{async block@matrix_sdk_base::client::BaseClient::receive_sync_response::{closure#0}::{closure#0}}>`
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/tracing-0.1.44/src/instrument.rs:266:16
     |
 266 |     pub struct Instrumented<T> {
     |                ^^^^^^^^^^^^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-base-0.14.1/src/client.rs:564:31
     |
 564 |       ) -> Result<SyncResponse> {
     |  _______________________________^
 565 | |         self.receive_sync_response_with_requested_required_states(
 566 | |             response,
 567 | |             &RequestedRequiredStates::default(),
 568 | |         )
 569 | |         .await
 570 | |     }
     | |_____^
     = note: required for `Unique<impl futures::Future<Output = Result<matrix_sdk_base::sync::SyncResponse, matrix_sdk_base::error::Error>>>` to implement `std::marker::Send`
note: required because it appears within the type `Box<impl futures::Future<Output = Result<matrix_sdk_base::sync::SyncResponse, matrix_sdk_base::error::Error>>>`
    --> library/alloc/src/boxed.rs:234:11
note: required because it appears within the type `std::pin::Pin<Box<impl futures::Future<Output = Result<matrix_sdk_base::sync::SyncResponse, matrix_sdk_base::error::Error>>>>`
    --> library/core/src/pin.rs:1094:11
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-0.14.0/src/sync.rs:153:35
     |
 153 |       ) -> Result<BaseSyncResponse> {
     |  ___________________________________^
 154 | |         let response = Box::pin(self.base_client().receive_sync_response(response)).await?;
...    |
 162 | |         Ok(response)
 163 | |     }
     | |_____^
note: required because it's used within this `async` block
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-0.14.0/src/client/mod.rs:2364:5
     |
2364 |     #[instrument(skip(self))]
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `MaybeDangling<{async block@matrix_sdk::Client::sync_once::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/maybe_dangling.rs:76:11
note: required because it appears within the type `ManuallyDrop<{async block@matrix_sdk::Client::sync_once::{closure#0}::{closure#0}}>`
    --> library/core/src/mem/manually_drop.rs:161:11
note: required because it appears within the type `Instrumented<{async block@matrix_sdk::Client::sync_once::{closure#0}::{closure#0}}>`
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/tracing-0.1.44/src/instrument.rs:266:16
     |
 266 |     pub struct Instrumented<T> {
     |                ^^^^^^^^^^^^
note: required because it's used within this `async` fn body
    --> /usr/obj/ports/iamb-0.0.11/iamb-0.0.11/modcargo-crates/matrix-sdk-0.14.0/src/client/mod.rs:2368:31
     |
2368 |       ) -> Result<SyncResponse> {
     |  _______________________________^
...    |
2411 | |         Ok(SyncResponse::new(next_batch, response))
...
```
(shortened for 'brevity')

using the hint from the compiler helps going past the build failure (credits to  @botovq):
```
+Index: src/main.rs
+--- src/main.rs.orig
++++ src/main.rs
+@@ -11,6 +11,7 @@
+ //!
+ //! Most rendering logic lives under the [windows] module, but [Matrix messages][message] have
+ //! their own module.
++#![recursion_limit = "256"]
+ #![allow(clippy::manual_range_contains)]
+ #![allow(clippy::needless_return)]
+ #![allow(clippy::result_large_err)]
```
i don't know rust so i don't know if that's the right fix, but at least it's out there :)

**Comment by VAWVAW** [comment]
This is an [upstream isssue](https://github.com/matrix-org/matrix-rust-sdk/issues/6254) and using the higher `recursion_limit` seems to be the accepted workaround until this problem is fixed by `matrix-sdk` or `rustc`.

**Comment by 0323pin** [comment]
Same issue on NetBSD build severs, https://releng.netbsd.org/pkgreports/shadow/HEAD/NetBSD-11.0-x86_64/20260407.1802/iamb-0.0.11/build.log

**Comment by ulyssa** [comment]
Merged #599 to fix this, until upstream prepares a better solution.

**Comment by ulyssa** [comment]
Re-opening since I realized last night that #599 doesn't completely fix this; the `#![recursion_limit = "..."]` bit needs to go in the crate hitting it. It looks like there's some progress towards making it possible to configure for downstream crates in https://github.com/rust-lang/trait-system-refactor-initiative/issues/268 and https://github.com/rust-lang/rust/issues/153132 though.

**Comment by botovq** [comment]
@ulyssa It did work around the build failure with Rust 1.94. Are you saying it breaks again with Rust 1.95?

**Comment by VAWVAW** [comment]
Yes, with rust 1.94 the downstream consumers of `matrix-sdk` would break while with rust 1.95 `matrix-sdk` itself seems to break. That is something that needs to be fixed upstream.

**Comment by aclindsa** [comment]
@VAWVAW @ulyssa It looks like matrix-sdk has released 0.16.1 (and also 0.17.0), either of which carry the fix for the recursion depth error: https://github.com/matrix-org/matrix-rust-sdk/issues/6551#issuecomment-4411522869

Can we update this in upstream iamb? (I confirmed `sed -ri 's/0\.16\.0/0\.16\.1/g' Cargo.toml` allows me to compile iamb with the latest b10c98588bd9b22a83dd1275fbf797023aba4117 with `rustc --version` of "rustc 1.95.0 (59807616e 2026-04-14) (Arch Linux rust 1:1.95.0-1)"). Here's a PR to make that change if you're interested: https://github.com/ulyssa/iamb/pull/619.

**Comment by ulyssa** [comment]
This has now been resolved by #625.
